spring:
  messaging:
    stomp:
      broker:
        relay:
          host: ${RABBITMQ_HOST}
          port: ${RABBITMQ_STOMP_PORT}
          username:  ${RABBITMQ_USERNAME}
          password:  ${RABBITMQ_PASSWORD}
        applicationDestinationPrefixes:
          - /app
        userDestinationPrefix: /user

  web:
    websocket:
      enabled: true
      origin: "*"
