spring:
  data:
    cassandra:
      contact-points: ${CASSANDRA_CONTACT_POINTS:localhost}
      port: ${CASSANDRA_PORT:9042}
      keyspace-name: ${CASSANDRA_KEYSPACE:near_connect}
      username: ${CASSANDRA_USERNAME:cassandra}
      password: ${CASSANDRA_PASSWORD:cassandra}
      local-datacenter: ${CASSANDRA_LOCAL_DATACENTER:datacenter1}
      schema-action: ${CASSANDRA_SCHEMA_ACTION}
  cache:
    type: redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:password}
      timeout: ${REDIS_TIMEOUT:6000}

  web:
    websocket:
      enabled: true
      origin: "*"
